---
- name: Ensure gcc is installed
  package:
    name: gcc
    state: present

- name: Create Minecraft group
  group:
    name: minecraft
    state: present
    
- name: Setup Minecraft user
  user:
    name: minecraft
    system: true
    create_home: true
    home: /opt/minecraft
    shell: /bin/bash
    groups: minecraft
    state: present

- name: Create directories for Minecraft
  file:
    path: /opt/minecraft/{{ item }}
    state: directory
  loop:
    - tools
    - server