---
- name: Stop saving
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "save-off"\015'

- name: Initiate save
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "save-all"\015'

- name: Compress world directory
  archive:
    path: /opt/minecraft/server/world
    dest: /opt/minecraft/server/backup/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}.zip
    format: zip

- name: Start saving
  command:
    cmd: /usr/bin/screen -p 0 -S mc -X eval 'stuff "save-on"\015'