---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - assert:
        that:
          - MODPACK_NAME is defined
          - MODPACK_URL is defined
          - MODPACK_TYPE is defined
          - RCON_PASSWORD is defined
          - WHITELIST_ENABLE is defined

  tasks:
    - name: Initial server requirements
      include_role:
        name: roles/mc-install
        tasks_from: 1-mc-init.yml

    - name: Create MC server files
      include_role:
        name: roles/mc-install
        tasks_from: 2-mc-files.yml

    - name: Install and configure FTB server
      include_role:
        name: roles/mc-install
        tasks_from: 3-mc-server.yml